fix: validation error (#52)
Seeing this error on render:
```
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
```
Express app now sets trust proxy to 1, which will resolve the rate limit
validation error when running behind Docker or a reverse proxy